# 数据库 及 Redis 配置
spring:
  redis:
    host: localhost
    port: 6379
#  使用 MySQL 不用做任何修改
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10

# Mybatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true    # 驼峰命名转换
